name: Lhx Reset 0312

on:
  workflow_run:
    workflows: ["Build CI Lhx Reset 0312"]
    branches:
      - "ci/lhx-reset-0312"
    types:
      - completed


jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 49.232.152.95
          username: syner
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: | 
            echo 111